### PR TITLE
Custom cook cycles and Binary_Sensors

### PR DESCRIPTION
**Pull request by njobrien1006**
Also seems to have open pull request #38 in here.

B.Sensor
- Add Binary_Sensor.py and add calls to add on init.
- Add translations for Binary_Sensor.

Numbers = CookCycle
- Add to numbers.py the cook_cycle entity.
- Embed the service.yaml.
- Other Cleanup/UIpdates.

Pull Request in relation to Feature Request #39

### CODE REVIEW

**Comment by sebirdman** [comment]
@njobrien1006 this looks good! i merged the first MR and will merge this once the conflicts are resolved.

**Comment by njobrien1006** [comment]
@sebirdman should be resolved and ready.

**Comment by sebirdman** [comment]
@njobrien1006 looks like this still can't be rebased on github. 

i've merged https://github.com/sebirdman/hass_traeger/pull/42 as well. some of this looks like it's a little overlapping (the probe sensor stuff on 42 looks to be pretty complete. but your work on the timer side still looks good to go.

**Comment by njobrien1006** [comment]
@sebirdman Rebased, Squashed, Re-PR'd #43 

I had put the Probe in there for testing when working with stephenpapierski prior to that PR. Can certainly take it out.

**Pull request closed without merging**
